<template>
  <div>
    <h1>Home</h1>
    <p>
      <img src="~/assets/img/guy-at-desk.png" alt="A graphic novel styled image of a guy at a computer desk - generated by midjourney" />
      <em class="caption">(I don't really look like this, but I do have lots of monitors)</em>
    </p>
    <hr />
    <p>
      Hello! I'm Kevin Kelly. I'm a software engineer. Here, I write about software development, technology, and other things that interest me. If you are looking for my more personal thoughts about improv and life. Check out <NuxtLink to="https://kevinmullaney.com">kevinmullaney.com</NuxtLink>.
    </p>
  </div>
</template>

<script setup lang="ts">

</script>

<style scoped>
img {
  max-width: 100%;
  height: auto;
}

.caption {
  font-size: 0.7em;
  color: #666;
}
</style>